### ISSUE TITLE
[Bug]: Dolphin cant launch games when file include non english char

### ISSUE THREAD

**Issue by bip-bop** [libretro/dolphin#375]
### Dolphin version

83438f9

### RetroArch version

1.21.0

### Platform

Windows

### Renderer

Vulkan

### Game exhibiting the issue

all

### Describe the issue

Dolphin emu can't launch the games if the folder name includes non-English characters (for me it was 'ü', 'ö')

### Log Output

not nececery

**Comment by gouchi** [comment]
It might be RA issue but can you provide some log, ["it's necessary"](https://www.youtube.com/watch?v=6ixvpLCdqkA) ;)

Thank you.

**Comment by bip-bop** [comment]
> It might be RA issue 
The other cores work fine, and the older version of Dolphin also works fine. If I rename the directory using only English characters, Dolphin works with the new version as well.








>it's necessary
oky my bad

[INFO] [Core]: Using content: "D:\emülatör_oyunlar\GameCube\Paper Mario - The Thousand-Year Door (USA).iso".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] RetroArch 1.21.0 (Git 54af661)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.21.0
[INFO] Git: 54af661
[INFO] Built: Apr 28 2025
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "E:\SteamLibrary\steamapps\common\RetroArch\cores\dolphin_libretro.dll"
[INFO] [Overrides]: Redirecting save file to "E:\SteamLibrary\steamapps\common\RetroArch\saves\dolphin-emu\Paper Mario - The Thousand-Year Door (USA).srm".
[INFO] [Overrides]: Redirecting save state to "E:\SteamLibrary\steamapps\common\RetroArch\states\dolphin-emu\Paper Mario - The Thousand-Year Door (USA).state".
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SAVE_DIRECTORY: "E:\SteamLibrary\steamapps\common\RetroArch\saves\dolphin-emu".
[INFO] [Environ]: SYSTEM_DIRECTORY: "E:\SteamLibrary\steamapps\common\RetroArch\system".
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "E:\SteamLibrary\steamapps\common\RetroArch\downloads".
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_LOG_INTERFACE.
[libretro INFO] 01:10:616 DolphinLibretro/Boot.cpp:108 I[COMMON]: User Directory set to 'E:\SteamLibrary\steamapps\common\RetroArch\saves\dolphin-emu/User'
[libretro INFO] 01:10:616 DolphinLibretro/Boot.cpp:109 I[COMMON]: System Directory set to 'E:\SteamLibrary\steamapps\common\RetroArch\system/dolphin-emu/Sys'
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2.
[ERROR] [Environ]: GET_VARIABLE: dolphin_main_cpu_thread - Invalid value.
[libretro INFO] 01:10:663 DolphinLibretro/Boot.cpp:357 I[BOOT]: CPU Core: JIT64
[libretro INFO] 01:10:663 DolphinLibretro/Boot.cpp:358 I[BOOT]: Fastmem enabled = Yes
[libretro INFO] 01:10:663 DolphinLibretro/Boot.cpp:359 I[BOOT]: JIT debug enabled = No
[INFO] [Environ]: GET_PREFERRED_HW_RENDER, video driver name: d3d11.
[INFO] [Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_D3D11.
[INFO] [Environ]: SET_HW_RENDER, context type: d3d11.
[INFO] Requesting D3D11 context.
[libretro INFO] 01:10:984 DolphinLibretro/Boot.cpp:366 N[Video]: Using GFX backend: D3D
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[libretro INFO] 01:10:994 DolphinLibretro/Boot.cpp:104 I[COMMON]: Suppressed popup: Warning - The specified file "D:/emülatör_oyunlar/GameCube/Paper Mario - The Thousand-Year Door (USA).iso" does not exist
[libretro ERROR] 01:10:994 DolphinLibretro/Boot.cpp:405 E[BOOT]: Could not boot D:\emülatör_oyunlar\GameCube\Paper Mario - The Thousand-Year Door (USA).iso
[ERROR] [Content]: Failed to load content
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[libretro INFO] 01:10:994 VideoBackends/D3D/D3DBase.cpp:167 N[Video]: Successfully released all device references!
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..

**Comment by cscd98** [comment]
Is this the old core? Did you download it or compile yourself?

I tried to reproduce using the new core, in Windows 11 and it works for me.

**Comment by bip-bop** [comment]
> Is this the old core? Did you download it or compile yourself?

No it's not old core, tested with fresh install core downloaded and updated from retroarch, 


>  Windows 11 and it works for me.

is your ROM folder name include chars like "ö,ç,ş,ğ,ü,", if I change the folder name works flawless as always 

Here is the fresh log. I'm getting the same results with the new update. The only problem is dolphin core, which cannot find folders whose names include characters such as "ö, ç, ş, ğ, ü". I can use it with English-named folders, but that's obviously a temporary solution.




[INFO] [Content]: Updating firmware status for: "E:\retro\retroarch_standalone 1.21\cores\dolphin_libretro.dll" on "E:\retro\retroarch_standalone 1.21\system".
[INFO] [Core]: Using content: "D:\emülatör_oyunlar\GameCube\Paper Mario - The Thousand-Year Door (USA).iso".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] RetroArch 1.21.0 (Git 54af661)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.21.0
[INFO] Git: 54af661
[INFO] Built: Apr 28 2025
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "E:\retro\retroarch_standalone 1.21\cores\dolphin_libretro.dll"
[INFO] [Overrides]: Redirecting save file to "E:\retro\retroarch_standalone 1.21\saves\dolphin-emu\Paper Mario - The Thousand-Year Door (USA).srm".
[INFO] [Overrides]: Redirecting save state to "E:\retro\retroarch_standalone 1.21\states\dolphin-emu\Paper Mario - The Thousand-Year Door (USA).state".
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SAVE_DIRECTORY: "E:\retro\retroarch_standalone 1.21\saves\dolphin-emu".
[INFO] [Environ]: SYSTEM_DIRECTORY: "E:\retro\retroarch_standalone 1.21\system".
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "E:\retro\retroarch_standalone 1.21\downloads".
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_LOG_INTERFACE.
[libretro INFO] 49:19:443 DolphinLibretro/Boot.cpp:108 I[COMMON]: User Directory set to 'E:\retro\retroarch_standalone 1.21\saves\dolphin-emu/User'
[libretro INFO] 49:19:443 DolphinLibretro/Boot.cpp:109 I[COMMON]: System Directory set to 'E:\retro\retroarch_standalone 1.21\system/dolphin-emu/Sys'
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2.
[ERROR] [Environ]: GET_VARIABLE: dolphin_main_cpu_thread - Invalid value.
[libretro INFO] 49:19:489 DolphinLibretro/Boot.cpp:357 I[BOOT]: CPU Core: JIT64
[libretro INFO] 49:19:489 DolphinLibretro/Boot.cpp:358 I[BOOT]: Fastmem enabled = Yes
[libretro INFO] 49:19:489 DolphinLibretro/Boot.cpp:359 I[BOOT]: JIT debug enabled = No
[INFO] [Environ]: GET_PREFERRED_HW_RENDER, video driver name: d3d11.
[INFO] [Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_D3D11.
[INFO] [Environ]: SET_HW_RENDER, context type: d3d11.
[INFO] Requesting D3D11 context.
[libretro INFO] 49:19:767 DolphinLibretro/Boot.cpp:366 N[Video]: Using GFX backend: D3D
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[libretro INFO] 49:19:774 DolphinLibretro/Boot.cpp:104 I[COMMON]: Suppressed popup: Warning - The specified file "D:/emülatör_oyunlar/GameCube/Paper Mario - The Thousand-Year Door (USA).iso" does not exist
[libretro ERROR] 49:19:774 DolphinLibretro/Boot.cpp:405 E[BOOT]: Could not boot D:\emülatör_oyunlar\GameCube\Paper Mario - The Thousand-Year Door (USA).iso
[ERROR] [Content]: Failed to load content
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[libretro INFO] 49:19:774 VideoBackends/D3D/D3DBase.cpp:167 N[Video]: Successfully released all device references!
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..

**Comment by gouchi** [comment]
Hi,

Not sure is it because Dolphin Libretro don't use [filestream](https://github.com/libretro/RetroArch/blob/master/libretro-common/streams/file_stream.c) which is using [VFS](https://github.com/libretro/RetroArch/tree/master/libretro-common/vfs) ?

[Source](https://github.com/libretro/RetroArch/issues/6051#issuecomment-358699046)

P.S = I can't reproduce this issue on Linux.

**Comment by bip-bop** [comment]
> Not sure is it because Dolphin

I'm not sure. I only experience it on the updated Dolphin core; the older Dolphin and other cores work fine. Its cant pathfind only after the update if file name include somthing like "ö, ç, ş, ğ, ü".

**Comment by cscd98** [comment]
I'll take another look at it.

**Comment by cscd98** [comment]
Fixed in https://github.com/libretro/dolphin/pull/376

**Comment by gouchi** [comment]
@bip-bop If you don't reproduce this issue with latest updated core, please close this issue.

Thank you.

**Comment by bip-bop** [comment]
Unfortunately, I'm still experiencing the same problem after the update. I thought maybe its just me problem, so I tested it on a different computer with a fresh install of RetroArch and a fresh install of the game, but it was still the same. If I put any of the letters "ö, ç, ş, ğ, ü" in my game folder, the updated Dolphin still can't find the game. Here are the logs. I'm going to put both the working and non-working ones in to compare. Also, one of the members who can access Windows should test it differently to me.

I also tested the game with the standalone Dolphin emulator, and it worked fine. 

Also, English is not my main language, if I say something weird, ignore it, pls 

working game log;
(The game launches and I wait a couple of seconds, then close I RetroArch.)
`[INFO] [Content] Updating firmware status for: "E:\retro\RetroArch-Win64\cores\dolphin_libretro.dll" on "E:\retro\RetroArch-Win64\system".
[INFO] [Core] Using content: "D:\emu\Paper Mario - The Thousand-Year Door (USA).iso".
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
[INFO] RetroArch 1.22.1 (Git 9f9a984)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.22.1
[INFO] Git: 9f9a984
[INFO] Built: Nov 15 2025
[INFO] =================================================
[INFO] [Input] Found input driver: "dinput".
[INFO] [Core] Loading dynamic libretro core from: "E:\retro\RetroArch-Win64\cores\dolphin_libretro.dll".
[INFO] [Override] Redirecting save file to "E:\retro\RetroArch-Win64\saves\dolphin-emu\Paper Mario - The Thousand-Year Door (USA).srm".
[INFO] [Override] Redirecting save state to "E:\retro\RetroArch-Win64\states\dolphin-emu\Paper Mario - The Thousand-Year Door (USA).state".
[INFO] [Environ] SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Content] Content loading skipped. Implementation will load it on its own.
[INFO] [Environ] GET_SAVE_DIRECTORY: "E:\retro\RetroArch-Win64\saves\dolphin-emu".
[INFO] [Environ] GET_SYSTEM_DIRECTORY: "E:\retro\RetroArch-Win64\system".
[INFO] [Environ] GET_CORE_ASSETS_DIRECTORY: "E:\retro\RetroArch-Win64\downloads".
[INFO] [Environ] SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ] GET_LOG_INTERFACE.
[libretro INFO] 14:30:402 DolphinLibretro/Boot.cpp:106 I[COMMON]: User Directory set to 'E:\retro\RetroArch-Win64\saves\dolphin-emu/User'
[libretro INFO] 14:30:402 DolphinLibretro/Boot.cpp:107 I[COMMON]: System Directory set to 'E:\retro\RetroArch-Win64\system/dolphin-emu/Sys'
[INFO] [Environ] GET_CORE_OPTIONS_VERSION.
[INFO] [Environ] SET_CORE_OPTIONS_V2.
[libretro INFO] 14:30:523 DolphinLibretro/Boot.cpp:365 I[BOOT]: CPU Core: JIT64
[libretro INFO] 14:30:523 DolphinLibretro/Boot.cpp:366 I[BOOT]: Fastmem enabled = Yes
[libretro INFO] 14:30:523 DolphinLibretro/Boot.cpp:367 I[BOOT]: JIT debug enabled = No
[INFO] [Environ] GET_PREFERRED_HW_RENDER, video driver: "d3d11"...
[INFO] [Environ] GET_PREFERRED_HW_RENDER: RETRO_HW_CONTEXT_D3D11.
[INFO] [Environ] SET_HW_RENDER, context type: d3d11.
[INFO] [HW] Requesting D3D11 context.
[libretro INFO] 14:30:780 DolphinLibretro/Boot.cpp:374 N[Video]: Using GFX backend: D3D
[INFO] [Environ] GET_RUMBLE_INTERFACE.
[libretro INFO] 14:31:139 Common/FileUtil.cpp:802 I[COMMON]: CreateSysDirectoryPath: Setting to E:\retro\RetroArch-Win64\system/dolphin-emu/Sys/
[libretro INFO] 14:31:142 Core/ConfigManager.cpp:263 N[CORE]: Active title: Paper Mario: The Thousand-Year Door (G8ME01)
[libretro INFO] 14:31:148 Core/Core.cpp:1041 N[COMMON]: Want determinism <- false
[libretro INFO] 14:31:148 Core/Core.cpp:255 I[BOOT]: Starting core = GameCube mode
[libretro INFO] 14:31:148 Core/Core.cpp:256 I[BOOT]: CPU Thread separate = Yes
[INFO] [Environ] SET_CONTROLLER_INFO.
[INFO] [SRAM] Skipping SRAM load.
[INFO] [Core] Version of libretro API: 1, Compiled against API: 1
[INFO] [Core] Geometry: 640x528, Aspect: 1.333, FPS: 59.94, Sample rate: 32029.00 Hz.
[INFO] [Video] Set video size to: 1440x1080.
[INFO] [Video] Using HW render, d3d11 driver forced.
[WARN] [DInput] Strong rumble unavailable.
[WARN] [DInput] Weak rumble unavailable.
[INFO] [Input] Found joypad driver: "dinput".
[INFO] [Autoconf] DualSense configured in port 1.
[INFO] [D3D11] Device created (Feature Level: 11.0)
[INFO] [D3D11] Flip model and tear control supported and enabled.
[INFO] [D3D11] Requesting 1 maximum frame latency, using 1.
[INFO] [D3D11] Found GPU at index 0: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 1: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 2: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 3: "Microsoft Basic Render Driver".
[INFO] [D3D11] Using GPU index 0.
[INFO] [Video] Found display server: "win32".
[libretro WARN] 14:32:315 VideoBackends/D3DCommon/Shader.cpp:289 W[Video]: ps_5_0 compilation succeeded with warnings:
E:\retro\RetroArch-Win64\Shader@0x000000001CB5E050(72,19-42): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
E:\retro\RetroArch-Win64\Shader@0x000000001CB5E050(148,17-39): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
E:\retro\RetroArch-Win64\Shader@0x000000001CB5E050(152,17-39): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
E:\retro\RetroArch-Win64\Shader@0x000000001CB5E050(156,17-39): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
E:\retro\RetroArch-Win64\Shader@0x000000001CB5E050(160,17-39): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values [libretro INFO] 14:32:363 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 0 cached shaders from E:/retro/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-uber-vs-2461FF40.cache
[libretro INFO] 14:32:363 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 0 cached shaders from E:/retro/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-uber-ps-2461FF40.cache
[libretro INFO] 14:32:363 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 0 cached shaders from E:/retro/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-gs-2461FF40.cache
[libretro INFO] 14:32:364 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 0 cached shaders from E:/retro/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-specialized-vs-G8ME01-2461FF40.cache
[libretro INFO] 14:32:364 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 0 cached shaders from E:/retro/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-specialized-ps-G8ME01-2461FF40.cache
[libretro INFO] 14:32:365 VideoCommon/ShaderCache.cpp:990 I[Video]: Read 0 pipeline UIDs from E:/retro/RetroArch-Win64/saves/dolphin-emu/User/Cache/G8ME01.uidcache
[INFO] [Audio] Set audio input rate to: 32061.03 Hz.
[INFO] [WASAPI] Client initialized (shared, PCM, 48000Hz, 64.0ms).
[INFO] [Audio] Started synchronous audio driver.
[INFO] [Microphone] Initialized microphone driver.
[INFO] [Display] Found display driver: "d3d11".
[INFO] [MIDI] Output device: "Microsoft GS Wavetable Synth".
[INFO] [Environ] SET_INPUT_DESCRIPTORS.
[INFO] [Environ] SET_INPUT_DESCRIPTORS.
[INFO] [Environ] SET_INPUT_DESCRIPTORS.
[INFO] [Environ] SET_INPUT_DESCRIPTORS.
[INFO] [Playlist] Loading favorites file: "E:\retro\RetroArch-Win64\playlists\builtin\content_favorites.lpl".
[INFO] [Playlist] Written to file: "E:\retro\RetroArch-Win64\playlists\builtin\content_history.lpl".
[INFO] [Playlist] Written to file: "E:\retro\RetroArch-Win64\playlists\builtin\content_music_history.lpl".
[INFO] [Playlist] Written to file: "E:\retro\RetroArch-Win64\playlists\builtin\content_video_history.lpl".
[INFO] [Playlist] Written to file: "E:\retro\RetroArch-Win64\playlists\builtin\content_image_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_image_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_music_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_video_history.lpl".
[INFO] [Playlist] Written to file: "E:\retro\RetroArch-Win64\playlists\builtin\content_history.lpl".
[libretro INFO] 14:32:835 Core/Boot/Boot.cpp:521 N[BOOT]: Booting from disc: D:/emu/Paper Mario - The Thousand-Year Door (USA).iso
[INFO] [Runtime] Content ran for a total of: 00 hours, 00 minutes, 13 seconds.
[INFO] [Runtime] Saving runtime log file: "E:\retro\RetroArch-Win64\playlists\logs\Dolphin\Paper Mario - The Thousand-Year Door (USA).lrtl".
[INFO] [Core] No content, starting dummy core.
[INFO] [Core] Unloading game...
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
[INFO] [Core] Saved core options file to "E:\retro\RetroArch-Win64\config\dolphin-emu\dolphin-emu.opt".
[INFO] RetroArch 1.22.1 (Git 9f9a984)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.22.1
[INFO] Git: 9f9a984
[INFO] Built: Nov 15 2025
[INFO] =================================================
[INFO] [Input] Found input driver: "dinput".
[INFO] [Environ] SET_PIXEL_FORMAT: RGB565.
[INFO] [Core] Version of libretro API: 1, Compiled against API: 1
[INFO] [Core] Geometry: 320x240, Aspect: 1.333, FPS: 165.00, Sample rate: 48000.00 Hz.
[INFO] [Video] Set video size to: 960x720.
[WARN] [DInput] Strong rumble unavailable.
[WARN] [DInput] Weak rumble unavailable.
[INFO] [Input] Found joypad driver: "dinput".
[INFO] [Autoconf] DualSense configured in port 1.
[INFO] [D3D11] Device created (Feature Level: 11.0)
[INFO] [D3D11] Flip model and tear control supported and enabled.
[INFO] [D3D11] Requesting 1 maximum frame latency, using 1.
[INFO] [D3D11] Found GPU at index 0: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 1: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 2: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 3: "Microsoft Basic Render Driver".
[INFO] [D3D11] Using GPU index 0.
[INFO] [Video] Found display server: "win32".
[INFO] [Audio] Set audio input rate to: 48000.00 Hz.
[INFO] [Video] Timings deviate too much. Will not adjust. (Target = 60.00 Hz, Game = 165.00 Hz)
[INFO] [Video] Game FPS > Monitor FPS. Cannot rely on VSync.
[INFO] [WASAPI] Client initialized (shared, PCM, 48000Hz, 64.0ms).
[INFO] [Audio] Started synchronous audio driver.
[INFO] [Microphone] Initialized microphone driver.
[INFO] [Display] Found display driver: "d3d11".
[INFO] [MIDI] Output device: "Microsoft GS Wavetable Synth".
[INFO] [Playlist] Loading favorites file: "E:\retro\RetroArch-Win64\playlists\builtin\content_favorites.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_image_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_music_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_video_history.lpl".
[INFO] [Config] Saved config to "E:\retro\RetroArch-Win64\retroarch.cfg".
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
`

not working game log;
(The game never launches after I put 'ş' in the game folder name.)
`[INFO] RetroArch 1.22.1 (Git 9f9a984)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.22.1
[INFO] Git: 9f9a984
[INFO] Built: Nov 15 2025
[INFO] =================================================
[INFO] [Input] Found input driver: "dinput".
[INFO] [Environ] SET_PIXEL_FORMAT: RGB565.
[INFO] [Core] Version of libretro API: 1, Compiled against API: 1
[INFO] [Core] Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[INFO] [Video] Set video size to: 960x720.
[INFO] [XInput] Found XInput v1.4.
[WARN] [DInput] Strong rumble unavailable.
[WARN] [DInput] Weak rumble unavailable.
[INFO] [Input] Found joypad driver: "dinput".
[INFO] [Autoconf] DualSense configured in port 1.
[INFO] [D3D11] Device created (Feature Level: 11.0)
[INFO] [D3D11] Flip model and tear control supported and enabled.
[INFO] [D3D11] Requesting 1 maximum frame latency, using 1.
[INFO] [D3D11] Found GPU at index 0: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 1: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 2: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 3: "Microsoft Basic Render Driver".
[INFO] [D3D11] Using GPU index 0.
[INFO] [Video] Found display server: "win32".
[INFO] [Audio] Set audio input rate to: 48000.00 Hz.
[INFO] [WASAPI] Client initialized (shared, PCM, 48000Hz, 64.0ms).
[INFO] [Audio] Started synchronous audio driver.
[INFO] [Microphone] Initialized microphone driver.
[INFO] [Display] Found display driver: "d3d11".
[INFO] [MIDI] Output device: "Microsoft GS Wavetable Synth".
[INFO] [Playlist] Loading favorites file: "E:\retro\RetroArch-Win64\playlists\builtin\content_favorites.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_image_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_music_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\RetroArch-Win64\playlists\builtin\content_video_history.lpl".
[INFO] [Content] Updating firmware status for: "E:\retro\RetroArch-Win64\cores\dolphin_libretro.dll" on "E:\retro\RetroArch-Win64\system".
[INFO] [Core] Using content: "D:\emuş\Paper Mario - The Thousand-Year Door (USA).iso".
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
[INFO] RetroArch 1.22.1 (Git 9f9a984)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.22.1
[INFO] Git: 9f9a984
[INFO] Built: Nov 15 2025
[INFO] =================================================
[INFO] [Input] Found input driver: "dinput".
[INFO] [Core] Loading dynamic libretro core from: "E:\retro\RetroArch-Win64\cores\dolphin_libretro.dll".
[INFO] [Override] Redirecting save file to "E:\retro\RetroArch-Win64\saves\dolphin-emu\Paper Mario - The Thousand-Year Door (USA).srm".
[INFO] [Override] Redirecting save state to "E:\retro\RetroArch-Win64\states\dolphin-emu\Paper Mario - The Thousand-Year Door (USA).state".
[INFO] [Environ] SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Content] Content loading skipped. Implementation will load it on its own.
[INFO] [Environ] GET_SAVE_DIRECTORY: "E:\retro\RetroArch-Win64\saves\dolphin-emu".
[INFO] [Environ] GET_SYSTEM_DIRECTORY: "E:\retro\RetroArch-Win64\system".
[INFO] [Environ] GET_CORE_ASSETS_DIRECTORY: "E:\retro\RetroArch-Win64\downloads".
[INFO] [Environ] SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ] GET_LOG_INTERFACE.
[libretro INFO] 18:27:592 DolphinLibretro/Boot.cpp:106 I[COMMON]: User Directory set to 'E:\retro\RetroArch-Win64\saves\dolphin-emu/User'
[libretro INFO] 18:27:592 DolphinLibretro/Boot.cpp:107 I[COMMON]: System Directory set to 'E:\retro\RetroArch-Win64\system/dolphin-emu/Sys'
[INFO] [Environ] GET_CORE_OPTIONS_VERSION.
[INFO] [Environ] SET_CORE_OPTIONS_V2.
[libretro INFO] 18:27:602 DolphinLibretro/Boot.cpp:365 I[BOOT]: CPU Core: JIT64
[libretro INFO] 18:27:602 DolphinLibretro/Boot.cpp:366 I[BOOT]: Fastmem enabled = Yes
[libretro INFO] 18:27:602 DolphinLibretro/Boot.cpp:367 I[BOOT]: JIT debug enabled = No
[INFO] [Environ] GET_PREFERRED_HW_RENDER, video driver: "d3d11"...
[INFO] [Environ] GET_PREFERRED_HW_RENDER: RETRO_HW_CONTEXT_D3D11.
[INFO] [Environ] SET_HW_RENDER, context type: d3d11.
[INFO] [HW] Requesting D3D11 context.
[libretro INFO] 18:27:865 DolphinLibretro/Boot.cpp:374 N[Video]: Using GFX backend: D3D
[INFO] [Environ] GET_RUMBLE_INTERFACE.
[libretro INFO] 18:27:874 DolphinLibretro/Boot.cpp:102 I[COMMON]: Suppressed popup: Warning - The specified file "D:/emuş/Paper Mario - The Thousand-Year Door (USA).iso" does not exist
[libretro ERROR] 18:27:874 DolphinLibretro/Boot.cpp:417 E[BOOT]: Could not boot D:\emuş\Paper Mario - The Thousand-Year Door (USA).iso
[ERROR] [Content] Failed to load content.
[libretro INFO] 18:27:874 VideoBackends/D3D/D3DBase.cpp:167 N[Video]: Successfully released all device references!
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
`

**Comment by bip-bop** [comment]
Sorry, logs look like a mess. Here are the log files; 

[working.log](https://github.com/user-attachments/files/23630316/working.log)

[non-working.log](https://github.com/user-attachments/files/23630321/non-working.log)

**Comment by cscd98** [comment]
@bip-bop Took me a while to look into this again as I don't use Windows.

But, I tried the latest core which is working for me:

[libretro INFO] 24:25:745 Core/Boot/Boot.cpp:521 N[BOOT]: Booting from disc: C:/emuş/New Super Mario Bros. Wii.iso

Could you make sure you have the latest nightly installed? The reason being your log doesn't have line "SCM Git revision" in it so it is not the latest version.

Also can you confirm you are using Windows 11 or 10 if it doesn't work.

**Comment by bip-bop** [comment]
first of thank you for your interest and patience @cscd98 .
unfortuntly still same for me 😪😔
I download nightly retroarch from buildbot this time, I use online downloader section to download dolphin and update it then I use core system file downloader dolphin.zip

I use windows 11

this time I enebled other logging options too 
working one;

[INFO] [Core] Using content: "E:\retro\emu\Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).wbfs".
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
[INFO] RetroArch 1.22.2 (Git e808120)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.22.2
[INFO] Git: e808120
[INFO] Built: Dec  9 2025
[INFO] =================================================
[INFO] [Input] Found input driver: "dinput".
[INFO] [Core] Loading dynamic libretro core from: "E:\retro\retroarch\RetroArch-Win64\cores\dolphin_libretro.dll".
[INFO] [Override] Redirecting save file to "E:\retro\retroarch\RetroArch-Win64\saves\dolphin-emu\Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).srm".
[INFO] [Override] Redirecting save state to "E:\retro\retroarch\RetroArch-Win64\states\dolphin-emu\Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).state".
[INFO] [Environ] SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Content] Content loading skipped. Implementation will load it on its own.
[INFO] [Environ] GET_SAVE_DIRECTORY: "E:\retro\retroarch\RetroArch-Win64\saves\dolphin-emu".
[INFO] [Environ] GET_SYSTEM_DIRECTORY: "E:\retro\retroarch\RetroArch-Win64\system".
[INFO] [Environ] GET_CORE_ASSETS_DIRECTORY: "E:\retro\retroarch\RetroArch-Win64\downloads".
[INFO] [Environ] SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ] GET_LOG_INTERFACE.
[libretro INFO] 52:35:581 DolphinLibretro/Boot.cpp:107 I[COMMON]: SCM Git revision: df2b1a754bba4f0595d3ed07ccd0711019e014b8
[libretro INFO] 52:35:581 DolphinLibretro/Boot.cpp:108 I[COMMON]: User Directory set to 'E:\retro\retroarch\RetroArch-Win64\saves\dolphin-emu/User'
[libretro INFO] 52:35:581 DolphinLibretro/Boot.cpp:109 I[COMMON]: System Directory set to 'E:\retro\retroarch\RetroArch-Win64\system/dolphin-emu/Sys'
[INFO] [Environ] GET_CORE_OPTIONS_VERSION.
[INFO] [Environ] SET_CORE_OPTIONS_V2.
[libretro INFO] 52:35:592 DolphinLibretro/Boot.cpp:367 I[BOOT]: CPU Core: JIT64
[libretro INFO] 52:35:592 DolphinLibretro/Boot.cpp:368 I[BOOT]: Fastmem enabled = Yes
[libretro INFO] 52:35:592 DolphinLibretro/Boot.cpp:369 I[BOOT]: JIT debug enabled = No
[INFO] [Environ] GET_PREFERRED_HW_RENDER, video driver: "d3d11"...
[INFO] [Environ] GET_PREFERRED_HW_RENDER: RETRO_HW_CONTEXT_D3D11.
[INFO] [Environ] SET_HW_RENDER, context type: d3d11.
[INFO] [HW] Requesting D3D11 context.
[libretro INFO] 52:35:867 DolphinLibretro/Boot.cpp:376 N[Video]: Using GFX backend: D3D
[INFO] [Environ] GET_RUMBLE_INTERFACE.
[libretro WARN] 52:35:876 Common/DirectIOFile.cpp:113 W[COMMON]: CreateFile: Sistem belirtilen dosyayı bulamıyor.

[libretro INFO] 52:35:876 Common/FileUtil.cpp:802 I[COMMON]: CreateSysDirectoryPath: Setting to E:\retro\retroarch\RetroArch-Win64\system/dolphin-emu/Sys/
[libretro INFO] 52:35:879 Core/ConfigManager.cpp:263 N[CORE]: Active title: Super Mario Galaxy (RMGP01)
[libretro INFO] 52:35:885 Core/Core.cpp:1041 N[COMMON]: Want determinism <- false
[libretro INFO] 52:35:904 Core/Core.cpp:255 I[BOOT]: Starting core = Wii mode
[libretro INFO] 52:35:904 Core/Core.cpp:256 I[BOOT]: CPU Thread separate = Yes
[INFO] [Environ] SET_CONTROLLER_INFO.
[INFO] [SRAM] Skipping SRAM load.
[INFO] [Core] Version of libretro API: 1, Compiled against API: 1
[INFO] [Core] Geometry: 640x528, Aspect: 1.778, FPS: 59.94, Sample rate: 32000.00 Hz.
[INFO] [Video] Set video size to: 1920x1079.
[INFO] [Video] Using HW render, d3d11 driver forced.
[WARN] [DInput] Strong rumble unavailable.
[WARN] [DInput] Weak rumble unavailable.
[INFO] [Input] Found joypad driver: "dinput".
[INFO] [Autoconf] DualSense configured in port 1.
[INFO] [D3D11] Device created (Feature Level: 11.0)
[INFO] [D3D11] Flip model and tear control supported and enabled.
[INFO] [D3D11] Requesting 1 maximum frame latency, using 1.
[INFO] [D3D11] Found GPU at index 0: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 1: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 2: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [D3D11] Found GPU at index 3: "Microsoft Basic Render Driver".
[INFO] [D3D11] Using GPU index 0.
[INFO] [Video] Found display server: "win32".
[libretro WARN] 52:37:071 VideoBackends/D3DCommon/Shader.cpp:289 W[Video]: ps_5_0 compilation succeeded with warnings:
E:\retro\retroarch\RetroArch-Win64\Shader@0x0000000007290F00(72,19-42): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
E:\retro\retroarch\RetroArch-Win64\Shader@0x0000000007290F00(148,17-39): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
E:\retro\retroarch\RetroArch-Win64\Shader@0x0000000007290F00(152,17-39): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
E:\retro\retroarch\RetroArch-Win64\Shader@0x0000000007290F00(156,17-39): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
E:\retro\retroarch\RetroArch-Win64\Shader@0x0000000007290F00(160,17-39): warning X3571: pow(f, e) will not work for negative f, u[libretro INFO] 52:37:118 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 0 cached shaders from E:/retro/retroarch/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-uber-vs-2461FF40.cache
[libretro INFO] 52:37:119 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 0 cached shaders from E:/retro/retroarch/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-uber-ps-2461FF40.cache
[libretro INFO] 52:37:119 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 0 cached shaders from E:/retro/retroarch/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-gs-2461FF40.cache
[libretro INFO] 52:37:119 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 4 cached shaders from E:/retro/retroarch/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-specialized-vs-RMGP01-2461FF40.cache
[libretro INFO] 52:37:120 VideoCommon/ShaderCache.cpp:267 I[Video]: Loaded 5 cached shaders from E:/retro/retroarch/RetroArch-Win64/saves/dolphin-emu/User/Cache/Shaders/D3D-specialized-ps-RMGP01-2461FF40.cache
[libretro INFO] 52:37:120 VideoCommon/ShaderCache.cpp:990 I[Video]: Read 8 pipeline UIDs from E:/retro/retroarch/RetroArch-Win64/saves/dolphin-emu/User/Cache/RMGP01.uidcache
[INFO] [Audio] Set audio input rate to: 32032.00 Hz.
[INFO] [WASAPI] Client initialized (shared, PCM, 48000Hz, 64.0ms).
[INFO] [Audio] Started synchronous audio driver.
[INFO] [Microphone] Initialized microphone driver.
[INFO] [Display] Found display driver: "d3d11".
[INFO] [MIDI] Output device: "Microsoft GS Wavetable Synth".
[INFO] [Environ] SET_INPUT_DESCRIPTORS.
[INFO] [Environ] SET_INPUT_DESCRIPTORS.
[INFO] [Environ] SET_INPUT_DESCRIPTORS.
[INFO] [Environ] SET_INPUT_DESCRIPTORS.
[INFO] [Playlist] Loading favorites file: "E:\retro\retroarch\RetroArch-Win64\playlists\builtin\content_favorites.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\retroarch\RetroArch-Win64\playlists\builtin\content_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\retroarch\RetroArch-Win64\playlists\builtin\content_image_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\retroarch\RetroArch-Win64\playlists\builtin\content_music_history.lpl".
[INFO] [Playlist] Loading history file: "E:\retro\retroarch\RetroArch-Win64\playlists\builtin\content_video_history.lpl".
[libretro INFO] 52:37:561 Core/Boot/Boot.cpp:521 N[BOOT]: Booting from disc: E:/retro/emu/Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).wbfs
[INFO] [Config] Saved config to "E:\retro\retroarch\RetroArch-Win64\retroarch.cfg".
[INFO] [Runtime] Content ran for a total of: 00 hours, 00 minutes, 03 seconds.
[INFO] [Runtime] Saving runtime log file: "E:\retro\retroarch\RetroArch-Win64\playlists\logs\Dolphin\Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).lrtl".
[INFO] [Core] Unloading game...
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
[INFO] [Core] Saved core options file to "E:\retro\retroarch\RetroArch-Win64\config\dolphin-emu\dolphin-emu.opt".
[INFO] [PERF] Performance counters (RetroArch):

not working one;

[INFO] [Core] Using content: "E:\retro\emuş\Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).wbfs".
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
[INFO] RetroArch 1.22.2 (Git e808120)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.22.2
[INFO] Git: e808120
[INFO] Built: Dec  9 2025
[INFO] =================================================
[INFO] [Input] Found input driver: "dinput".
[INFO] [Core] Loading dynamic libretro core from: "E:\retro\retroarch\RetroArch-Win64\cores\dolphin_libretro.dll".
[INFO] [Override] Redirecting save file to "E:\retro\retroarch\RetroArch-Win64\saves\dolphin-emu\Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).srm".
[INFO] [Override] Redirecting save state to "E:\retro\retroarch\RetroArch-Win64\states\dolphin-emu\Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).state".
[INFO] [Environ] SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Content] Content loading skipped. Implementation will load it on its own.
[INFO] [Environ] GET_SAVE_DIRECTORY: "E:\retro\retroarch\RetroArch-Win64\saves\dolphin-emu".
[INFO] [Environ] GET_SYSTEM_DIRECTORY: "E:\retro\retroarch\RetroArch-Win64\system".
[INFO] [Environ] GET_CORE_ASSETS_DIRECTORY: "E:\retro\retroarch\RetroArch-Win64\downloads".
[INFO] [Environ] SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ] GET_LOG_INTERFACE.
[libretro INFO] 53:57:303 DolphinLibretro/Boot.cpp:107 I[COMMON]: SCM Git revision: df2b1a754bba4f0595d3ed07ccd0711019e014b8
[libretro INFO] 53:57:303 DolphinLibretro/Boot.cpp:108 I[COMMON]: User Directory set to 'E:\retro\retroarch\RetroArch-Win64\saves\dolphin-emu/User'
[libretro INFO] 53:57:303 DolphinLibretro/Boot.cpp:109 I[COMMON]: System Directory set to 'E:\retro\retroarch\RetroArch-Win64\system/dolphin-emu/Sys'
[INFO] [Environ] GET_CORE_OPTIONS_VERSION.
[INFO] [Environ] SET_CORE_OPTIONS_V2.
[libretro INFO] 53:57:314 DolphinLibretro/Boot.cpp:367 I[BOOT]: CPU Core: JIT64
[libretro INFO] 53:57:315 DolphinLibretro/Boot.cpp:368 I[BOOT]: Fastmem enabled = Yes
[libretro INFO] 53:57:315 DolphinLibretro/Boot.cpp:369 I[BOOT]: JIT debug enabled = No
[INFO] [Environ] GET_PREFERRED_HW_RENDER, video driver: "d3d11"...
[INFO] [Environ] GET_PREFERRED_HW_RENDER: RETRO_HW_CONTEXT_D3D11.
[INFO] [Environ] SET_HW_RENDER, context type: d3d11.
[INFO] [HW] Requesting D3D11 context.
[libretro INFO] 53:57:599 DolphinLibretro/Boot.cpp:376 N[Video]: Using GFX backend: D3D
[INFO] [Environ] GET_RUMBLE_INTERFACE.
[libretro INFO] 53:57:608 DolphinLibretro/Boot.cpp:103 I[COMMON]: Suppressed popup: Warning - The specified file "E:/retro/emuş/Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).wbfs" does not exist
[libretro ERROR] 53:57:608 DolphinLibretro/Boot.cpp:419 E[BOOT]: Could not boot E:\retro\emuş\Super Mario Galaxy (Europe, Australia) (En,Fr,De,Es,It).wbfs
[ERROR] [Content] Failed to load content.
[libretro INFO] 53:57:608 VideoBackends/D3D/D3DBase.cpp:167 N[Video]: Successfully released all device references!
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
